### PR TITLE
isValidTerm() now validates ontology terms for which OLS returns mult…

### PR DESCRIPTION
**Pull request by rolando-ebi**
isValidTerm() now validates ontology terms for which OLS returns mult…iple results, rather than just 1 result

### CODE REVIEW

**Comment by rolando-ebi** [comment]
> As we use this URL: "https://www.ebi.ac.uk/ols/api/terms/findByIdAndIsDefiningOntology?id=" this always has to return only 1 result if the ID is correct. If it is returning more, then there is a bug in OLS.

I agree, but I think we should make this change anyway to unblock us. This change is backwards compatible with valid metadata

**Comment by mcourtot** [comment]
@simonjupp indicated that the expected behaviour for OLS is one term and one term only and encouraged us to report those cases where it were not true as OLS bugs. If the OLS documentation doesn't reflect this then it should be reported on their side. 

>Note that there is a condition where the term is valid, but has no defining ontology. In this case the chosen method would return zero results when the term does in fact exist in OLS.

Can you please add an example? As far as I understood from @simonjupp this should also not happen and would need to be reported.

Given the fact that to be valid under current conditions there should only be one term, I don't think the right behaviour is to relax the validation rules with the argument that 'they are backwards compatible'; we could remove all validation and be backwards compatible too ;)


Taking a step back: 
- for the validator we have chosen a strict approach to validation based on users requirements, including HCA's. If there are different requirements for a less strict validation we should investigate those and determine whether we want to relax the validator's behaviour. I'd like to carefully consider those though before making fixes in our codebase for bugs in a third-party resource.
- for this specific issue, we agreed on a fix timeline with HCA and possible remediation steps should this not be resolved by Thursday.

**Comment by tburdett** [comment]
> Can you please add an example? As far as I understood from @simonjupp this should also not happen and would need to be reported

I don't have an example. But the "should" is the kicker here. If we do not allow for the possibility that this happens and guard against it (by e.g. throwing an error), we have no ability to report it. We'll see silent fails, or else report terms that a user can find in OLS as invalid (as we've done previously), causing a lot of confusion for users.

> Given the fact that to be valid under current conditions there should only be one term, I don't think the right behaviour is to relax the validation rules

Agreed that we shouldn't be relaxing validation rules. But observing those cases and handling them is defensive programming, not changing the behaviour of the validator. I think we **should** allow for the scenario that OLS (a third party service) may give imperfect results, and catch those cases where our assumptions break down. 

The validation requirement seems to demand "exactly one matching term for the given ID". OLS doesn't provide that answer easily, so the code (if this change is accepted) will translate that into "exactly one matching term for the given ID, in at least one ontology that is judged by OLS to be the defining ontology". Now that isn't the same thing. But neither is "exactly one matching term for the given ID, in exactly one ontology that is judged by OLS to be the defining ontology". We're picking an approximation either way. It seems inexpensive to check for other responses from OLS (e.g. we got >1 result) and use these unexpected results to throw user-friendly exceptions that we can monitor and report to OLS. What is the counter-argument to doing that?

**Comment by mcourtot** [comment]
Totally agree on the logging and reporting (we've had similar cases in the past and did indeed improve error messages eg with taxonomy in NCBI not being valid for ENA)

However I don't think that this is what this commit is about: the proposed change here is that if we find one or more terms the validation should pass, which is not the currently accepted behaviour. 

If we want to change what should be valid or not that's a discussion we can have (and it'd be good to have the feedback from OLS when we do) In the meantime I would prefer to not do quick fixes in the code to bypass current validation rules.

**Comment by tburdett** [comment]
> the proposed change here is that if we find one or more terms the validation should pass

I guess this depends on the ID you use. I earlier posited the behaviour as coded is:

> exactly one matching term for the given ID, in at least one ontology that is judged by OLS to be the defining ontology.

That isn't strictly true: this code uses the 'id' parameter (e.g. EFO:0000001) as the search ID, so you run the risk of hitting a collision. Actually this code now performs the test **"at least one matching term for the given ID in at least one ontology judged by OLS to be the defining ontology"**. If you get >1 result from OLS, this could be due to (at least) two conditions:

1. Your ID matches two different terms (two different IRIs), or
1. Your ID matches a single term, but OLS has judged multiple ontologies as the "defining" ontology

Using 'id' makes life much more complicated. 2. should clearly be valid. But 1. completely confuses me - should the doc be valid because the term is valid? Or invalid because there's a collision? How would a user provide the "correct" id?

**Comment by ke4** [comment]
@rolando-ebi : We discussed this PR with Laura and Melanie: if the OLS team is not fixing their bug by Thursday, then I am going to merge this PR temporarily, but revert it back as soon as they fixed it.

**Comment by ke4** [comment]
This OLS behaviour is confuses me. If the defining ontology should only give us 0 or 1 result, then more than 1 result is clearly a bug in OLS. They should check their result, before returning it to the user and if it is more than 1, then return some kind of error message would be better and then we would not have this confusion.

**Comment by mcourtot** [comment]
Thanks everybody for the feedback! @henrietteharmse reports this is now fixed so I'll close this.
A couple of comments to follow on offline:
- I don't think this is strictly speaking an OLS bug; they can't guarantee what users will upload, and even if they test they wouldn't necessarily be able to update. I for one would be upset if they were to start curating my resource on my behalf.
- While I don't think in this case this fix was the right way to handle the issue, I agree with the general statement that DSP should better handle error cases (whether from ENA, OLS or anywhere else)
- Finally, we need to discuss the ontology validation behaviour. We know we can't rely on OLS only, as there are cases where terms are not in OLS for example. We need to figure out what we intent to do in general for ontology validation and then adapt the code in the ELIXIR validator.

**Pull request closed without merging**
